feat: sse events
dhis2-sre/im-manager pull request #791
Opened 2024-06-13 08:11 UTC by teleivo

2024-06-20 13:00 UTC, tonsV2 requested changes

2024-06-20 13:28 UTC, teleivo commented on pkg/event/handler.go
> +	var base, maxJitter uint = 3_000, 1_001
https://pkg.go.dev/math/rand/v2#Uint32 uses a half-open interval [0,n) so 1000ms+1ms

2024-06-20 13:32 UTC, teleivo commented on pkg/event/handler.go
> +	logger := h.logger.WithGroup("consumer").With("name", consumerName)
We should declare vars as close to their usage as possible. Moving it further down.

2024-06-20 13:34 UTC, teleivo commented on pkg/event/handler.go
> +			c.Render(-1, sseEvent)
https://github.com/gin-gonic/gin/blob/9c081de9cdd1948f521d47d170d18cbc2981c33a/context.go#L1128-L1134

2024-06-20 14:07 UTC, tonsV2 commented on pkg/event/handler.go
> +	if kindProperty, ok := message.ApplicationProperties["kind"]; ok {
I was planning on listening for named events. Do you have other plans? :slightly_smiling_face:

2024-06-21 10:41 UTC, tonsV2 requested changes

2024-06-21 10:52 UTC, teleivo commented on pkg/event/event_integration_test.go
> +	event5 := eventEmitter.emit(t, "db-update", sharedGroup.Name, user1)
they are not received by anyone as we use offset spec next meaning you only get messages after you subscribed

2024-06-21 11:28 UTC, tonsV2 approved these changes

2024-06-21 13:39 UTC, radnov approved these changes
🚀

2024-06-22 03:50 UTC, merged